version: '3.8'
services:
  web:
    image: nginx:alpine
    container_name: web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot
      - angular-app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done;'"

  copy-certs:
    image: alpine
    volumes:
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c "apk add --no-cache bash && ./copy-certs.sh"
    depends_on:
      - certbot

  angular-app:
    build: .
    ports:
      - "4200:80" # Map port 4200 on the host to port 80 on the container
