version: '3.8'
services:
  web:
    image: nginx:alpine
    container_name: web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/ubuntu/action-runner-fe/_work/frontend/frontend/certbot/conf:/etc/letsencrypt:ro
      - /home/ubuntu/action-runner-fe/_work/frontend/frontend/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot
      - angular-app
    networks:
      - backend_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/ubuntu/action-runner-fe/_work/frontend/frontend/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/action-runner-fe/_work/frontend/frontend/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done;'"

  angular-app:
    build: .
    ports:
      - "4200:80" # Map port 4200 on the host to port 80 on the container
    networks:
      - backend_network

networks:
  backend_network:
    external: true