name: Deployment workflow
on:
  push:
    branches: [depoyment-testing]
  workflow_dispatch:

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set Up ENV
        run: |
          echo "${{ secrets.SQL_URI }}" > .env
          
  deploy:
    runs-on: self-hosted
    needs: [checkout]
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
          timeout-minutes: 15

      - name: Bring down Docker containers
        run: |
          echo "Bringing down Docker containers"
          sudo docker-compose down
          echo "Docker containers brought down"

      - name: Build and bring up Docker containers
        run: |
          echo "Building and bringing up Docker containers"
          sudo docker-compose up --build -d || (echo "Docker compose failed" && exit 1)
          echo "Docker containers are up"

      - name: Prune Docker system
        run: |
          echo "Pruning Docker system"
          sudo docker system prune -a -f
          echo "Docker system pruned"