name: Deployment workflow
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set Up ENV
        run: |
          echo "${{ secrets.SQL_URI }}" > .env
  deploy:
    runs-on: self-hosted
    needs: [checkout]
    steps:
      - name: Start Nginx
        run: |
          sudo docker-compose up -d web
          
      - name: Obtain SSL certificates
        run: |
          sudo docker-compose run --rm certbot certonly --webroot --webroot-path=/var/www/certbot -d pokerparlor.club --email kalpitmody@gmail.com --agree-tos --no-eff-email

      - name: Restart services with SSL
        run: |
          sudo docker-compose down
          sudo docker-compose up -d
          sudo docker system prune -a