name: Deployment workflow
on:
  push:
    branches: [main]

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set Up ENV
        run: |
          echo "${{ secrets.SQL_URI }}" > .env
  deploy:
    runs-on: self-hosted
    needs: [checkout]
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.13'
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Check Node.js version
        run: node -v
      - name: Docker
        run: |
          sudo docker-compose down
          sudo docker-compose up --build -d
          sudo docker system prune -a